### ISSUE TITLE
Configuration Error

### ISSUE THREAD

**Issue by syedrazackimran** [noxt/ScrollableDatepicker#10]
Hi , 
herewith i attached screenshot of error what i'm facing. i don't know how to fix that error . kindly do need fully . thanks for advance 
<img width="967" alt="screen shot 2017-06-21 at 8 59 20 am" src="https://user-images.githubusercontent.com/15051045/27363669-24159b2c-5660-11e7-998c-20099436886a.png">

**Comment by noxt** [comment]
Hi! Fixed in version 2.0.1
