### ISSUE TITLE
Enhancement proposal for managing device rotation

### ISSUE THREAD

**Issue by RichardHB9** [noxt/ScrollableDatepicker#12]
Hi
To make your already very flexible framework even more useful on iPad  I have two proposals for enhancement:
1. Instead the fix numberOfDatesInOneScreen of the cells to be displayed, I will suggest to use the same cell width for all devices and orientation, and display so many, as collection view has space. To do this flexible:
2. I will suggest to define collection view in a storyboard and only load collection view cell definition from xib.

richard

**Comment by noxt** [comment]
Hello, Richard!

I have another solution: add property to configuration like this:
```swift
public struct Configuration {

    public enum DaySizeCalculationStrategy {
        case constant(CGFloat)
        case numberOfVisibleItems(Int)
    }

    public var daySizeCalculation: DaySizeCalculationStrategy = DaySizeCalculationStrategy.numberOfVisibleItems(5)
   
    ...
}
```

What do u thing about this?

**Comment by RichardHB9** [comment]
Hello Dmitry,
That sounds good. It will allow us to change the number of cells in relation to device size and device orientation. Good idea.
richard

**Comment by noxt** [comment]
Done in version 2.1.0

**Comment by RichardHB9** [comment]
Hello Dmitry,
Absolutely perfect!!! And you are faster then light (if it's possible ;-)
Thank you.
richard
