### ISSUE TITLE
datepicker.selectedDate not highlighted anymore

### ISSUE THREAD

**Issue by sdavidliu** [noxt/ScrollableDatepicker#14]
I created a button that just selects a new date programmatically with this code:
```
//Select tomorrow
@IBAction func buttonAction(_ sender: Any) {
    datepicker.selectedDate = Date().addingTimeInterval(24*60*60)
    print(datepicker.selectedDate) //I already checked that this line prints a different date
}
```
Before: https://user-images.githubusercontent.com/16772059/31089624-b0ba262a-a759-11e7-9475-61fa8c2bc1ba.png
After: https://user-images.githubusercontent.com/16772059/31089623-b0b943cc-a759-11e7-83a2-bef8d3d2a369.png

When I set a new date, the date picker doesn't visually show the selected date anymore. Is there a way to fix this or maybe is there a better method to use to select a new date programmatically?

**Comment by PalmerATX** [comment]
It's trying to match the dates including the time of the date values. I fixed this by resting all dates to the same time. 

```
extension Date {
    func resetTimeInDate() -> Date {
        let formatter = DateFormatter()
        formatter.dateStyle = .short
        let dateString = formatter.string(from: self)
        let thisDate = formatter.date(from: dateString)
        return thisDate!
    }
}
```

So the example view controller would be:
```
@IBOutlet weak var datepicker: ScrollableDatepicker!{
        didSet {
            var dates = [Date]()
            for day in -15...15 {
                let aDay = Date(timeIntervalSinceNow: Double(day * 86400))
                dates.append(aDay.resetTimeInDate())
            }

```

Hope this helps.

**Comment by sdavidliu** [comment]
Yes, it worked! Thank you!
