### ISSUE TITLE
Swift 4 support?

### ISSUE THREAD

**Issue by kapoorsahil** [noxt/ScrollableDatepicker#15]
Errors:

> 'UIFontWeightThin' was obsoleted in Swift 3

**Comment by iamjason** [comment]
@kapoorsahil,

If you're still in need of a Swift 4 version you can use this PR (https://github.com/noxt/ScrollableDatepicker/pull/16) until it's merged into master by adding this to your Podfile:

```  
pod 'ScrollableDatepicker', :git => 'https://github.com/iamjason/ScrollableDatepicker', :branch => 'swift-4'
```

**Comment by noxt** [comment]
Swift 4.2 support in new version `2.2.0`
