### ISSUE TITLE
Scroll to today date on button click with selection

### ISSUE THREAD

**Issue by Ghousepasha-ios** [noxt/ScrollableDatepicker#18]
How can i make when i click on button, the calendar should scroll to today current date with selection?

**Comment by noxt** [comment]
Hello mate! I released a new version `2.2.0`.

You can find solution in demo project or just use this code:
```swift
@IBAction func goToCurrentDate(_ sender: UIButton) {
    datepicker.selectedDate = Date()
    datepicker.scrollToSelectedDate(animated: true)
    showSelectedDate()
}
```
