### ISSUE TITLE
Not able to scroll todays date if I change the date picker day range.

### ISSUE THREAD

**Issue by dimplebhendarkar** [noxt/ScrollableDatepicker#6]
I want to show date with particular range. and date picker autoscroll to todays date when it load.
Just like follow
  dates = [Date]()
            for day in -15...15 {
                dates.append(Date(timeIntervalSinceNow: Double(day * 86400)))
            }

And I want to show default todays day as selected. so I set 
 datepicker.selectedDate = Date()

But It do not autoscroll to todays date. How to do that?

**Comment by noxt** [comment]
I added a new method in version `1.0.4`

```swift 
func scrollToSelectedDate(animated: Bool)
```

U can see example in [ViewController](https://github.com/noxt/ScrollableDatepicker/blob/master/ScrollableDatepicker/PresentationLayer/ViewController.swift)
