### ISSUE TITLE
Show Selected Date

### ISSUE THREAD

**Issue by FarhanAnsari92** [noxt/ScrollableDatepicker#8]
There is no option to show the date, or to horizontally centre the date that i wish to show. So the user can feel that the is by default selected.

**Comment by noxt** [comment]
I added a new method in version `1.0.4`

```swift 
func scrollToSelectedDate(animated: Bool)
```

U can see example in [ViewController](https://github.com/noxt/ScrollableDatepicker/blob/master/ScrollableDatepicker/PresentationLayer/ViewController.swift)
