### ISSUE TITLE
Distance between cells is changing after rotatio between portrait and landscape

### ISSUE THREAD

**Issue by RichardHB9** [noxt/ScrollableDatepicker#9]
Hi,
Thank you very much for the great project.
Could you please fix the device rotation changes between cell distance?
Also it will be very helpful, if this project will support "Universal" device, and not only iPhone.

Thank you,
richard

**Comment by noxt** [comment]
Hi! Fixed in version 2.0.1.

When rotating the device, I show the same number of days, which is specified in the config + scroll to selected day.

Alternatively, there was another thought to add to the config parameter for specifying the number of days for the landscape orientation.
